### ISSUE TITLE
All emails being BCC'ed to "mail@diginiq.net" is a major privacy/security issue

### ISSUE THREAD

**Issue by MagDevX** [arif-rh/ci4-auth#2]
Thank you for sharing your great work. For privacy/security reasons, either the hard coded BCC email `mail@diginiq.net` should be removed from `src/Auth.php`, or it should be mentioned in `README.md`.

**Comment by arif-rh** [comment]
Hi @MagDevX 

I have publish v0.3.1 as fixed of this issue.
