### ISSUE TITLE
Unable to connect to the database

### ISSUE THREAD

**Issue by AnwarQasem** [arif-rh/ci4-auth#3]
Hello, 

I've tried today the library ... and I have a small issue if you can help. 

I've done the migrate and everything, but when I wanted to test the login:
```
$login = new Auth\Auth();
return $login->login("some@email.com", "pass");
```

It's saying Unable to connect to the database . I mention that the database it's connected to ci4 in both .env and /app/Config/Database.php files. 

Any ideas ?

Regards, 
Anwar

**Comment by arif-rh** [comment]
Hello @AnwarQasem 

As it saying Unable to connect to the database, so the issue is on connecting state. Have you try to use it on development mode and see, which line of code was failed to connect to the database, so you can figure out what actually need to be fixed.

**Comment by AnwarQasem** [comment]
You are right, sorry for that .... the issue was from my Docker container. So not the library issue.

Thank you.
